matches:
  # Greetings (logged)
  - trigger: ";hi"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"$BSD_COPILOT_PATH/scripts/log_snippet.py\" \";hi\" \"Hi there, thanks for reaching out!\""

  - trigger: ";hello"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"$BSD_COPILOT_PATH/scripts/log_snippet.py\" \";hello\" \"Hello! Thanks for contacting BSD. How can I help you today?\""

  # Closings (logged)
  - trigger: ";thanks"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"$BSD_COPILOT_PATH/scripts/log_snippet.py\" \";thanks\" \"Thanks so much, and please don't hesitate to reach out if you have any other questions!\""

  - trigger: ";sig"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: |
            python3 "$BSD_COPILOT_PATH/scripts/log_snippet.py" ";sig" "Best regards,
            [Your Name]
            BSD Sales Team"

  # AI-powered polish (copy text first, then use trigger)
  # ;p1 = 1 polished version
  # ;p2 = 2 options to choose from
  # ;p3 = 3 options to choose from

  - trigger: ";p1"
    replace: "{{output}}"
    force_mode: keys
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"$BSD_COPILOT_PATH/scripts/polish.py\" 1"

  - trigger: ";p2"
    replace: "{{output}}"
    force_mode: keys
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"$BSD_COPILOT_PATH/scripts/polish.py\" 2"

  - trigger: ";p3"
    replace: "{{output}}"
    force_mode: keys
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"$BSD_COPILOT_PATH/scripts/polish.py\" 3"

  # AI-powered reply (copy customer question first, then use trigger)
  # ;reply = Generate response based on knowledge base
  - trigger: ";reply"
    replace: "{{output}}"
    force_mode: keys
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"$BSD_COPILOT_PATH/scripts/reply.py\""
